name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Code Quality & Security", "GitGuardian Secret Scan"]
    types:
      - completed
    branches: [ main ]

concurrency: production

jobs:
  deploy:
    if: ${{ workflows == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu

      - name: Build JAR
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE=nazim112/user-service
          TAG=${{ github.sha }}
          docker build -t $IMAGE:$TAG -t $IMAGE:latest .
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest